### PR TITLE
Fix off-by-one bug in serde impl for Symbol types

### LINKED ISSUE #88: Symbols deserialize incorrectly.
When deserializing symbols from eg. JSON the resulting values are off by one.

Example:

``` rust
use string_interner::{DefaultSymbol, StringInterner};

fn main() {
    let mut interner = StringInterner::default();
    let symbol = interner.get_or_intern("hello");

    let serialized = serde_json::to_string(&symbol).unwrap();
    println!("Original: {:?}, JSON: {}", symbol, serialized);

    let deserialized: DefaultSymbol = serde_json::from_str(&serialized).unwrap();
    println!("Deserialized: {:?}", deserialized);

    match interner.resolve(deserialized) {
        Some(s) => println!("Resolves to: {}", s),
        None => println!("Cannot resolve symbol!"),
    }
}
```

**Expected Output:**
```
Original: SymbolU32 { value: 1 }, JSON: 1
Deserialized: SymbolU32 { value: 1 }
Resolves to: hello
```

**Actual Output**
``` 
Original: SymbolU32 { value: 1 }, JSON: 1
Deserialized: SymbolU32 { value: 2 }
Cannot resolve symbol!
```

### PR DESCRIPTION
**Pull request by caspark**
The various Symbols' serde implementations had a bug that would cause their underlying index to increase by 1 each time they're serialized and deserialized, because the serialize impl didn't account for the fact that `Symbol::new()` adds one to guarantee that the resulting index is non-zero.

This fixes that and adds tests for it.

* A less obtuse fix would be to move the `+ 1` operation out of `Symbol::new()` and into the deserialize impl for each Symbol, but I'm not sure if something else in this codebase relies on `Symbol::new()` adding 1.
* Wasn't sure whether you want tests in serde_impl.rs or in the existing integration test binary; I opted for the former because it means the tests will neatly be automatically disabled if the serde feature is off.

---

Fixes #88 .

### CODE REVIEW

File: src/serde_impl.rs [hunk 1]
```diff
@@ -93,16 +93,22 @@ macro_rules! impl_serde_for_symbol {
                 &self,
                 serializer: T,
             ) -> ::core::result::Result<T::Ok, T::Error> {
-                self.value.serialize(serializer)
+                // When the value is deserialized below, it will be converted back to a non-zero
+                // type by adding 1 to the value, so we need to account for that here by subtracting
+                // 1 from the value.
+                let zeroable_value = self.value.get() - 1;
+                zeroable_value.serialize(serializer)
```
Comment (Robbepop) [inline src/serde_impl.rs:100]: This should use `Symbol::to_usize` which internally performs the `-1` if necessary. There are symbols that don't need this, e.g. `usize` can be a `Symbol` and for it, performing `-1` would be incorrect.

File: src/serde_impl.rs [hunk 2]
```diff
@@ -93,16 +93,22 @@ macro_rules! impl_serde_for_symbol {
...
         impl<'de> ::serde::Deserialize<'de> for $crate::symbol::$name {
             fn deserialize<D: ::serde::Deserializer<'de>>(
                 deserializer: D,
             ) -> ::core::result::Result<Self, D::Error> {
-                let index = <$ty as ::serde::Deserialize<'de>>::deserialize(deserializer)?;
-                let ::core::option::Option::Some(symbol) = Self::new(index) else {
+                let zeroable_value = <$ty as ::serde::Deserialize<'de>>::deserialize(deserializer)?;
+                // Symbol::new() will add 1 to the value to guarantee that the resulting underlying
+                // index will be non-zero.
+                let ::core::option::Option::Some(symbol) = Self::new(zeroable_value) else {
```
Comment (Robbepop) [inline src/serde_impl.rs:111]: The previous behavior was correct in my opinion. Non-zero symbol indices _must_ be non-zero. We serialize them to be 0-based (-1) and then we have to add (+1) again indeserialization.

**Review by Robbepop — CHANGES_REQUESTED** [review]
Thanks for the intended fixes. I have reviewed the changes. Please fix the nits I have. Ideally we could even make the `Symbol` (de)serialization more generic by implementing `(De)Serialize` for all `T: Symbol`.

File: src/serde_impl.rs (hunk 1 above)
Comment (caspark) [reply src/serde_impl.rs:100]: Ah, I didn't spot that Symbol is implemented for usize directly, and not just for SymbolUsize. Good point, will fix.

File: src/serde_impl.rs (hunk 2 above)
Comment (caspark) [reply src/serde_impl.rs:111]: Yes, agreed. But just to be clear, there is no behavior change in this diff: I just renamed `index` to `zeroable_value` and added the comment (both of which I now see are incorrect, as per your other comment).

**Comment by caspark** [comment]
Feedback should be addressed now. Swapped to using `from_usize()` in the `Deserialize` impl too, to clearly mirror the `Serialize` impl.

We can't impl serde traits for all `T: Symbol` unfortunately because of the orphan rule: it would cause overlapping trait impls for those traits - e.g. `usize` would have our impls and serde's impls.

File: src/serde_impl.rs [hunk 3]
```diff
@@ -119,3 +121,74 @@ macro_rules! impl_serde_for_symbol {
...
+        assert!(symbol_round_trip_serializes(
+            SymbolUsize::try_from_usize(42).unwrap()
+        ));
+        assert!(symbol_round_trip_serializes(
+            SymbolUsize::try_from_usize(usize::MAX as usize - 1).unwrap()
+        ));
+    }
+
+    #[test]
+    fn raw_usize_round_trips() {
```
Comment (caspark) [inline src/serde_impl.rs:183]: This is obviously a bit silly to include given that it's basically just exercising the trivial `try_from_usize` impl, so feel free to remove it if you want.

File: src/serde_impl.rs [hunk 4]
```diff
@@ -102,7 +102,9 @@ macro_rules! impl_serde_for_symbol {
                 deserializer: D,
             ) -> ::core::result::Result<Self, D::Error> {
                 let index = <$ty as ::serde::Deserialize<'de>>::deserialize(deserializer)?;
-                let ::core::option::Option::Some(symbol) = Self::new(index) else {
+                let ::core::option::Option::Some(symbol) =
+                    index.try_into().ok().and_then(Self::try_from_usize)
+                else {
```
Comment (Robbepop) [inline src/serde_impl.rs:107]: This is unnecessary since `Self::new` already does what was needed.
Please correct me if my assessment here is wrong.

Comment (Robbepop) [reply src/serde_impl.rs:107]: Just revert those changes.

File: src/serde_impl.rs (hunk 3 above)
Comment (Robbepop) [reply src/serde_impl.rs:183]: I think it is fine to have.

File: src/serde_impl.rs (hunk 4 above)
Comment (caspark) [reply src/serde_impl.rs]: Sure, Self::new() is what does the work so the extra level of indirection isn't necessary. In my eyes it's just nice to match the usage of to_usize() in the serialize impl, but it's matter of taste.

Anyway, I've reverted this change now as requested.

**Comment by caspark** [comment]
Latest feedback applied!

**Review by Robbepop — APPROVED** [review]
@caspark Thanks a lot for this!

**Comment by caspark** [comment]
No worries, thanks for the quick reviews!
