### PR TITLE
Fix use after free bug around `StringInterner::clone()`

### LINKED ISSUE #9: Unsoundness (use after free) around `StringInterner::clone()` and `InternalStrRef`
# Abstract
By steps below, call to `StringInterner::get_or_intern()` and `StringInterner::get()` cause **use after free** in `string-interner 0.7.0`.

1. Create a `StringInterner`. I'll call it `old`.
2. Intern some string.
2. Clone `old`. I'll call the newly created interner `old`.
    + `let new = old.clone();`.
3. Drop `old`.
    + At this point, all `Box<str>`s in `old.values` is also going to be dropped.
4. Call `new.get_or_intern()` or `new.get()`, passing same string as before.
    + These functions refer `Box<str>` strings already dropped. This is UB.

# Code to reproduce
```rust
// `string-interner = "=0.7.0"` in Cargo.toml.
use string_interner::{DefaultStringInterner, Sym};

fn clone_and_drop() -> (DefaultStringInterner, Sym) {
    let mut old = DefaultStringInterner::new();
    let foo = old.get_or_intern("foo");

    let new = old.clone();
    let _bar = old.get_or_intern("bar");

    (new, foo)
}

fn main() {
    let (mut new, foo) = clone_and_drop();
    assert_eq!(
        new.get_or_intern("foo"),
        foo,
        "`foo` should represent the string \"foo\" so they should be equal"
    );
}
```

```
$ cargo run
   Compiling string-interner-unsoundness-test v0.1.0 (/home/lo48576/works/public/playground/rust/string-interner-unsoundness-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/string-interner-unsoundness-test`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Sym(2)`,
 right: `Sym(1)`: `foo` should represent the string "foo" so they should be equal', src/main.rs:15:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
$
```

The last `assert_eq!` should never fail, but it failed in my environment.
(This is UB so it might success coincidentally...)

See  <https://github.com/lo48576/string-interner/blob/5bb5485c8479b2bfb40d83758c0db56f8f466efe/TEST_RESULT.md> for more detailed explanation.

### PR DESCRIPTION
**Pull request by lo48576**
New `Clone` implementation updates `StrInternalStrRef` pointers in `StringInterter::map` with cloned strings, to prevent referring string owned by another interner instance.

Fixes #9.

### CODE REVIEW

File: src/tests.rs [hunk 1]
```diff
@@ -373,3 +373,45 @@ mod from_iterator {
...
+// See <https://github.com/Robbepop/string-interner/issues/9>.
+mod clone_and_drop {
+	use super::*;
+
+	fn clone_and_drop() -> (DefaultStringInterner, Sym) {
+		let mut old = DefaultStringInterner::new();
+		let foo = old.get_or_intern("foo");
+
+		let new = old.clone();
+		let _bar = old.get_or_intern("bar");
```
Comment (Robbepop) [inline src/tests.rs]: Is this needed? Please add a comment.

File: src/tests.rs [hunk 2]
```diff
@@ -373,3 +373,45 @@ mod from_iterator {
...
+
+		(new, foo)
+	}
+
+	#[test]
+	fn no_use_after_free() {
+		let (mut new, foo) = clone_and_drop();
+
+		// This assert may fail if there are use after free bug.
```
Comment (Robbepop) [inline src/tests.rs]: Can we somehow force the test to fail if there is a use-after-free? E.g. by zero'ing all dropped memory?

File: src/tests.rs (hunk 1 above)
Comment (lo48576) [reply src/tests.rs]: At the time I wrote it, I was concerned about optimization, because `.clone()` seems completely unnecessary without `let _bar = old.get_or_intern(..);` and could be optimized away.

I confirmed that additional `.get_or_intern()` is unnecessary to reproduce the problem, so I'll remove it.

File: src/tests.rs (hunk 2 above)
Comment (lo48576) [reply src/tests.rs]: Using `Vec<Option<Box<str>>>` instead of `Vec<Box<str>>` can help a little to explicitly invalidate `InternalStrRef`s, but use-after-free is essentially undefined behavior and it may be impossible to detect that completely.
If another new value is allocated at the address where the dropped `Box<str>` was, it can be any valid (but not owned) value, so any flag or zero'ing cannot force every use-after-free to fail.

For this simple test, I think `Option<Box<str>>` would work, but it **is not guaranteed because it is UB**.

**Comment by lo48576** [comment]
* Removed unnecessary `.get_or_intern()` call.
* Rebased onto latest master.

**Comment by lo48576** [comment]
I noticed that the safety can be tested by checking that all raw pointers are referring to strings owned by the same interner.
I'll try it later and make PR if it works.

**Comment by Shnatsel** [comment]
@Robbepop since this was a critical security fix, please release a new version to crates.io ASAP.

Please also consider yanking vulnerable versions and/or backporting the fix to 0.6.x series, which according to crates.io stats still has some use.

**Comment by Robbepop** [comment]
Will do but keep in mind that even though you are totally right about everything you say I think that cloning a `StringInterner` is a rather uncommon operation. Maybe that's why this use-after-free bug was not uncovered for so long.
